version: "3"

services:

  server: 

    build: api/
    command: npm start
    ports: 
      - 4000:4000
    
  client:
    build : client/
    command: yarn start
    network_mode: host
    depends_on: 
      - server